In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import scipy.stats as stats
import os
import warnings
warnings.filterwarnings('ignore')
pd.options.display.max_columns = None
from IPython.display import display

In [17]:
file_path = os.path.join("..", "data", "processed", "feature_select.csv")

# Read CSV with index_col=0 to avoid unnamed column issues
data = pd.read_csv(file_path, index_col=0)
data

,Enrollment_ID,Study_Prog_Exam_Completed,Study_Prog_Group_Size,Student_Enrollment_Gap,Exit_Status,Study_Prog_Name_Accountancy,Study_Prog_Name_Allied_Medical_Care,Study_Prog_Name_Arts_Therapies,Study_Prog_Name_Bachelor_of_Law,Study_Prog_Name_Biology_Medical_Laboratory_Research,Study_Prog_Name_Built_Environment,Study_Prog_Name_Business_Administration,Study_Prog_Name_Cesar_Kinetics_Therapy,Study_Prog_Name_Chemical_Engineering,Study_Prog_Name_Chemistry,Study_Prog_Name_Communication,Study_Prog_Name_Communication_and_Multimedia_Design,Study_Prog_Name_Creative_Business,Study_Prog_Name_Dental_Hygiene,Study_Prog_Name_Educational_Theory,Study_Prog_Name_Electrical_and_Electronic_Engineering,Study_Prog_Name_Entrepreneurship_Retail_Management,Study_Prog_Name_Facility_Management,Study_Prog_Name_Finance_Control,Study_Prog_Name_Finance_Tax_and_Advice,Study_Prog_Name_Health_Care_Management,Study_Prog_Name_Human_Resource_Management,Study_Prog_Name_Industrial_Engineering_Management,Study_Prog_Name_Information_Communication_Technology,Study_Prog_Name_International_Business_Utrecht,Study_Prog_Name_Interpreter,Study_Prog_Name_Journalism,Study_Prog_Name_Logistics_Management,Study_Prog_Name_Marketing_Management,Study_Prog_Name_Mechanical_Engineering,Study_Prog_Name_Nursing,Study_Prog_Name_Optometry,Study_Prog_Name_Orthoptics,Study_Prog_Name_Pharmaceutical_Business_Administration,Study_Prog_Name_Physiotherapy,Study_Prog_Name_Primary_Education,Study_Prog_Name_Safety_and_Security_Management,Study_Prog_Name_Skin_Therapy,Study_Prog_Name_Social_Legal_Services,Study_Prog_Name_Social_Work,Study_Prog_Name_Speech_and_Language_Therapy,Study_Prog_Name_Teacher_Education,Prior_Edu_Type_BUITENL_SL,Prior_Edu_Type_EDUCATIE,Prior_Edu_Type_HAVO,Prior_Edu_Type_HBO,Prior_Edu_Type_MBO,Prior_Edu_Type_OVERIG,Prior_Edu_Type_Others,Prior_Edu_Type_VWO,Prior_Edu_School_Location_'S-GRAVENHAGE,Prior_Edu_School_Location_'S-HERTOGENBOSCH,Prior_Edu_School_Location_0000_ABROAD,Prior_Edu_School_Location_ALKMAAR,Prior_Edu_School_Location_ALMELO,Prior_Edu_School_Location_ALMERE,Prior_Edu_School_Location_ALPHEN_AAN_DEN_RIJN,Prior_Edu_School_Location_AMERSFOORT,Prior_Edu_School_Location_AMSTELVEEN,Prior_Edu_School_Location_AMSTERDAM,Prior_Edu_School_Location_APELDOORN,Prior_Edu_School_Location_ARNHEM,Prior_Edu_School_Location_ASSEN,Prior_Edu_School_Location_BAARN,Prior_Edu_School_Location_BARNEVELD,Prior_Edu_School_Location_BERGEN_NH,Prior_Edu_School_Location_BILTHOVEN,Prior_Edu_School_Location_BREDA,Prior_Edu_School_Location_BREUKELEN,Prior_Edu_School_Location_BUSSUM,Prior_Edu_School_Location_CAPELLE_AAN_DEN_IJSSEL,Prior_Edu_School_Location_CASTRICUM,Prior_Edu_School_Location_CULEMBORG,Prior_Edu_School_Location_DELFT,Prior_Edu_School_Location_DEVENTER,Prior_Edu_School_Location_DOETINCHEM,Prior_Edu_School_Location_DOORN,Prior_Edu_School_Location_DOORWERTH,Prior_Edu_School_Location_DORDRECHT,Prior_Edu_School_Location_EDE,Prior_Edu_School_Location_EINDHOVEN,Prior_Edu_School_Location_ELBURG,Prior_Edu_School_Location_ENSCHEDE,Prior_Edu_School_Location_ERMELO,Prior_Edu_School_Location_ETTEN-LEUR,Prior_Edu_School_Location_GORINCHEM,Prior_Edu_School_Location_GOUDA,Prior_Edu_School_Location_GRONINGEN,Prior_Edu_School_Location_HAARLEM,Prior_Edu_School_Location_HARDERWIJK,Prior_Edu_School_Location_HELMOND,Prior_Edu_School_Location_HENGELO_OV,Prior_Edu_School_Location_HILVERSUM,Prior_Edu_School_Location_HOOFDDORP,Prior_Edu_School_Location_HOORN_NH,Prior_Edu_School_Location_HOUTEN,Prior_Edu_School_Location_HUIZEN,Prior_Edu_School_Location_IJSSELSTEIN,Prior_Edu_School_Location_LAREN_NH,Prior_Edu_School_Location_LEERDAM,Prior_Edu_School_Location_LEEUWARDEN,Prior_Edu_School_Location_LEIDEN,Prior_Edu_School_Location_LELYSTAD,Prior_Edu_School_Location_MAARSSEN,Prior_Edu_School_Location_MAASTRICHT,Prior_Edu_School_Location_MIJDRECHT,Prior_Edu_School_Location_NIEUWEGEIN,Prior_Edu_School_Location_NIJKERK,Prior_Edu_School_Location_NIJMEGEN,Prior_Edu_School_Location_ONBEKEND,Prior_Edu_School_Location_Others,Prior_Edu_School_Location_PAPENDRECHT,Prior_Edu_School_Location_PURMEREND,Prior_Edu_School_Location_ROERMOND,Prior_Edu_School_Location_ROTTERDAM,Prior_Edu_School_Location_SCHOONHOVEN,Prior_Edu_School_Location_SLEEUWIJK,Prior_Edu_School_Location_SOEST,Prior_Edu_School_Location_TERNEUZEN,Prior_Edu_School_Location_TIEL,Prior_Edu_School_Location_TILBURG,Prior_Edu_School_Location_UITHOORN,Prior_Edu_School_Location_UTRECHT,Prior_Edu_School_Location_VEENENDAAL,Prior_Edu_School_Location_VLEUTEN,Prior_Edu_School_Location_VOORBURG,Prior_Edu_School_Location_VUGHT,Prior_Edu_School_Location_WAGENINGEN,Prior_Edu_School_Location_WARNSVELD,Prior_Edu_School_Location_WEESP,Prior_Edu_School_Location_WIJK_BIJ_DUURSTEDE,Prior_Edu_School_Location_WOERDEN,Prior_Edu_School_Location_ZAANDAM,Prior_Edu_School_Location_ZALTBOMMEL,Prior_Edu_School_Location_ZEIST,Prior_Edu_School_Location_ZEVENAAR,Prior_Edu_School_Location_ZOETERMEER,Prior_Edu_School_Location_ZUTPHEN,Prior_Edu_School_Location_ZWOLLE,Prior_Edu_Postcode_0000_ABROAD,Prior_Edu_Postcode_1033_SB,Prior_Edu_Postcode_1071_ED,Prior_Edu_Postcode_1078_VN,Prior_Edu_Postcode_1097_DZ,Prior_Edu_Postcode_1102_CV,Prior_Edu_Postcode_1211_EN,Prior_Edu_Postcode_1213_VB,Prior_Edu_Postcode_1215_PN,Prior_Edu_Postcode_1217_GH,Prior_Edu_Postcode_1217_PM,Prior_Edu_Postcode_1251_GB,Prior_Edu_Postcode_1273_JP,Prior_Edu_Postcode_1276_KD,Prior_Edu_Postcode_1325_PL,Prior_Edu_Postcode_1326_AA,Prior_Edu_Postcode_1333_VD,Prior_Edu_Postcode_1334_PA,Prior_Edu_Postcode_1382_CD,Prior_Edu_Postcode_1401_RT,Prior_Edu_Postcode_1405_HM,Prior_Edu_Postcode_1406_NR,Prior_Edu_Postcode_1422_MT,Prior_Edu_Postcode_1507_EK,Prior_Edu_Postcode_1817_BC,Prior_Edu_Postcode_1902_GT,Prior_Edu_Postcode_2012_BL,Prior_Edu_Postcode_2012_MN,Prior_Edu_Postcode_2012_WT,Prior_Edu_Postcode_2321_KS,Prior_Edu_Postcode_2334_CP,Prior_Edu_Postcode_2401_XH,Prior_Edu_Postcode_2402_NM,Prior_Edu_Postcode_2405_VS,Prior_Edu_Postcode_2521_DB,Prior_Edu_Postcode_2722_ZA,Prior_Edu_Postcode_2803_ZV,Prior_Edu_Postcode_2805_BP,Prior_Edu_Postcode_2805_SN,Prior_Edu_Postcode_2806_HP,Prior_Edu_Postcode_2871_HJ,Prior_Edu_Postcode_2871_JN,Prior_Edu_Postcode_3015_CX,Prior_Edu_Postcode_3032_AD,Prior_Edu_Postcode_3034_PT,Prior_Edu_Postcode_3067_MR,Prior_Edu_Postcode_3068_AV,Prior_Edu_Postcode_3071_AL,Prior_Edu_Postcode_3312_KW,Prior_Edu_Postcode_3401_RD,Prior_Edu_Postcode_3432_NA,Prior_Edu_Postcode_3435_XA,Prior_Edu_Postcode_3439_MV,Prior_Edu_Postcode_3443_CT,Prior_Edu_Postcode_3446_GL,Prior_Edu_Postcode_3452_MD,Prior_Edu_Postcode_3511_XX,Prior_Edu_Postcode_3512_VS,Prior_Edu_Postcode_3513_EX,Prior_Edu_Postcode_3521_GH,Prior_Edu_Postcode_3524_SG,Prior_Edu_Postcode_3526_AB,Prior_Edu_Postcode_3526_HL,Prior_Edu_Postcode_3527_XL,Prior_Edu_Postcode_3544_DA,Prior_Edu_Postcode_3562_CS,Prior_Edu_Postcode_3571_KH,Prior_Edu_Postcode_3572_LP,Prior_Edu_Postcode_3582_KA,Prior_Edu_Postcode_3607_GK,Prior_Edu_Postcode_3621_JK,Prior_Edu_Postcode_3641_XR,Prior_Edu_Postcode_3703_CV,Prior_Edu_Postcode_3706_TE,Prior_Edu_Postcode_3707_EP,Prior_Edu_Postcode_3707_GL,Prior_Edu_Postcode_3708_AG,Prior_Edu_Postcode_3723_BA,Prior_Edu_Postcode_3723_BV,Prior_Edu_Postcode_3742_CS,Prior_Edu_Postcode_3761_EV,Prior_Edu_Postcode_3771_KA,Prior_Edu_Postcode_3813_DC,Prior_Edu_Postcode_3813_DH,Prior_Edu_Postcode_3813_KD,Prior_Edu_Postcode_3813_VD,Prior_Edu_Postcode_3815_AG,Prior_Edu_Postcode_3817_EZ,Prior_Edu_Postcode_3817_KB,Prior_Edu_Postcode_3818_ET,Prior_Edu_Postcode_3818_KG,Prior_Edu_Postcode_3818_LA,Prior_Edu_Postcode_3822_CK,Prior_Edu_Postcode_3825_MP,Prior_Edu_Postcode_3842_LA,Prior_Edu_Postcode_3844_AS,Prior_Edu_Postcode_3851_ZJ,Prior_Edu_Postcode_3863_HV,Prior_Edu_Postcode_3904_JC,Prior_Edu_Postcode_3904_ZK,Prior_Edu_Postcode_3906_EA,Prior_Edu_Postcode_3941_ZX,Prior_Edu_Postcode_3962_KT,Prior_Edu_Postcode_3995_AX,Prior_Edu_Postcode_3995_DE,Prior_Edu_Postcode_4001_DN,Prior_Edu_Postcode_4003_KZ,Prior_Edu_Postcode_4102_BM,Prior_Edu_Postcode_4103_NM,Prior_Edu_Postcode_4143_AC,Prior_Edu_Postcode_4205_NK,Prior_Edu_Postcode_4207_EA,Prior_Edu_Postcode_4254_XD,Prior_Edu_Postcode_4535_HA,Prior_Edu_Postcode_4818_TA,Prior_Edu_Postcode_4873_LP,Prior_Edu_Postcode_5022_DD,Prior_Edu_Postcode_5042_EK,Prior_Edu_Postcode_5216_EG,Prior_Edu_Postcode_5223_GW,Prior_Edu_Postcode_5262_BS,Prior_Edu_Postcode_5301_DH,Prior_Edu_Postcode_5616_HR,Prior_Edu_Postcode_6042_JZ,Prior_Edu_Postcode_6224_DC,Prior_Edu_Postcode_6512_BT,Prior_Edu_Postcode_6525_EN,Prior_Edu_Postcode_6706_KN,Prior_Edu_Postcode_6713_MC,Prior_Edu_Postcode_6715_CW,Prior_Edu_Postcode_6717_LG,Prior_Edu_Postcode_6717_XA,Prior_Edu_Postcode_6812_AL,Prior_Edu_Postcode_6814_CJ,Prior_Edu_Postcode_6822_LR,Prior_Edu_Postcode_6824_LE,Prior_Edu_Postcode_6865_CZ,Prior_Edu_Postcode_6904_GZ,Prior_Edu_Postcode_7001_EA,Prior_Edu_Postcode_7231_NN,Prior_Edu_Postcode_7313_EC,Prior_Edu_Postcode_7314_NX,Prior_Edu_Postcode_7316_AW,Prior_Edu_Postcode_7329_BZ,Prior_Edu_Postcode_7331_VZ,Prior_Edu_Postcode_7414_AR,Prior_Edu_Postcode_7553_VZ,Prior_Edu_Postcode_8017_CA,Prior_Edu_Postcode_8024_AH,Prior_Edu_Postcode_8031_AA,Prior_Edu_Postcode_8081_VV,Prior_Edu_Postcode_8233_GA,Prior_Edu_Postcode_8932_NX,Prior_Edu_Postcode_9723_ZS,Prior_Edu_Postcode_Others,Prior_Edu_Country_NL,Prior_Edu_Country_outside_NL
0,1546413,1,347,164.0,leaving_unsuccessfully,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0
1,1549026,0,347,68.0,leaving_unsuccessfully,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0
2,1543665,1,347,49.0,leaving_unsuccessfully,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0
3,1556941,0,347,11.0,leaving_unsuccessfully,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0
4,1536214,1,347,63.0,leaving_unsuccessfully,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48386,1964301,0,1663,51.0,leaving_unsuccessfully,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0
48387,1966882,0,1663,51.0,leaving_unsuccessfully,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0
48388,1972247,1,1663,-16.0,leaving_successfully,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
48389,1973119,0,1663,99.0,leaving_unsuccessfully,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0
48390,1980114,1,1663,208.0,leaving_unsuccessfully,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0

In [18]:
print(data['Exit_Status'].value_counts())

Exit_Status
leaving_unsuccessfully    43154
switching_internally       3489
leaving_successfully       1748
Name: count, dtype: int64

In [19]:
# Define a mapping for Exit_Status
exit_status_mapping = {
    'leaving_successfully': 0,
    'switching_internally': 1,
    'leaving_unsuccessfully': 2
}

# Apply the mapping to replace categorical values with numbers
data['Exit_Status'] = data['Exit_Status'].map(exit_status_mapping)

# Show the first few rows to verify
print(data['Exit_Status'].value_counts())

Exit_Status
2    43154
1     3489
0     1748
Name: count, dtype: int64

Print only the pairs of columns with correlation above 0.7

In [20]:
# Convert Exit_Status to numeric values automatically (if not already done)
data['Exit_Status'] = data['Exit_Status'].astype('category').cat.codes  # This will assign 0,1,2 automatically

# Drop Enrollment_ID (since it's just an identifier)
data_numeric = data.drop(columns=['Enrollment_ID'])

# Compute correlation matrix
corr_matrix = data_numeric.corr()

# Find pairs with correlation above 0.7 (excluding self-correlation)
high_corr_pairs = []
threshold = 0.7

for col1 in corr_matrix.columns:
    for col2 in corr_matrix.columns:
        if col1 != col2 and corr_matrix.loc[col1, col2] > threshold:
            high_corr_pairs.append((col1, col2, corr_matrix.loc[col1, col2]))

# Remove duplicate pairs (since correlation is symmetric)
unique_high_corr_pairs = set(tuple(sorted(pair[:2])) + (pair[2],) for pair in high_corr_pairs)

# Print highly correlated column pairs
print("Highly Correlated Column Pairs (Above 70%):")
for col1, col2, corr in unique_high_corr_pairs:
    print(f"{col1} - {col2}: {corr:.2f}")

Highly Correlated Column Pairs (Above 70%):
Prior_Edu_Postcode_3863_HV - Prior_Edu_School_Location_NIJKERK: 1.00
Prior_Edu_Postcode_8233_GA - Prior_Edu_School_Location_LELYSTAD: 1.00
Prior_Edu_Postcode_1507_EK - Prior_Edu_School_Location_ZAANDAM: 0.72
Prior_Edu_Postcode_3771_KA - Prior_Edu_School_Location_BARNEVELD: 1.00
Prior_Edu_Postcode_7001_EA - Prior_Edu_School_Location_DOETINCHEM: 0.74
Prior_Edu_Postcode_5616_HR - Prior_Edu_School_Location_EINDHOVEN: 0.75
Prior_Edu_Postcode_3452_MD - Prior_Edu_School_Location_VLEUTEN: 1.00
Prior_Edu_Postcode_7231_NN - Prior_Edu_School_Location_WARNSVELD: 1.00
Prior_Edu_Postcode_4205_NK - Prior_Edu_School_Location_GORINCHEM: 0.76
Prior_Edu_Postcode_1251_GB - Prior_Edu_School_Location_LAREN_NH: 1.00
Prior_Edu_Postcode_3723_BV - Prior_Edu_School_Location_BILTHOVEN: 0.71
Prior_Edu_Postcode_4001_DN - Prior_Edu_School_Location_TIEL: 0.80
Prior_Edu_Postcode_0000_ABROAD - Prior_Edu_School_Location_0000_ABROAD: 0.96
Prior_Edu_Postcode_6042_JZ - Prior_Edu_School_Location_ROERMOND: 0.89
Prior_Edu_Postcode_3607_GK - Prior_Edu_School_Location_MAARSSEN: 1.00
Prior_Edu_Postcode_4143_AC - Prior_Edu_School_Location_LEERDAM: 1.00
Prior_Edu_Postcode_3621_JK - Prior_Edu_School_Location_BREUKELEN: 0.99
Prior_Edu_Postcode_0000_ABROAD - Prior_Edu_Type_BUITENL_SL: 0.85
Prior_Edu_Postcode_3941_ZX - Prior_Edu_School_Location_DOORN: 1.00
Prior_Edu_Postcode_7553_VZ - Prior_Edu_School_Location_HENGELO_OV: 0.89
Prior_Edu_Postcode_3641_XR - Prior_Edu_School_Location_MIJDRECHT: 1.00
Prior_Edu_Postcode_3995_DE - Prior_Edu_School_Location_HOUTEN: 0.94
Prior_Edu_Postcode_3312_KW - Prior_Edu_School_Location_DORDRECHT: 0.90
Prior_Edu_School_Location_0000_ABROAD - Prior_Edu_Type_BUITENL_SL: 0.87
Prior_Edu_Postcode_6224_DC - Prior_Edu_School_Location_MAASTRICHT: 0.74
Prior_Edu_Postcode_1902_GT - Prior_Edu_School_Location_CASTRICUM: 0.79
Prior_Edu_Postcode_3844_AS - Prior_Edu_School_Location_HARDERWIJK: 0.81
Prior_Edu_Postcode_1382_CD - Prior_Edu_School_Location_WEESP: 1.00
Prior_Edu_Postcode_5301_DH - Prior_Edu_School_Location_ZALTBOMMEL: 1.00
Prior_Edu_Postcode_5223_GW - Prior_Edu_School_Location_'S-HERTOGENBOSCH: 0.77
Prior_Edu_Postcode_1422_MT - Prior_Edu_School_Location_UITHOORN: 1.00
Prior_Edu_Postcode_1817_BC - Prior_Edu_School_Location_ALKMAAR: 0.72
Prior_Edu_Country_outside_NL - Prior_Edu_Type_BUITENL_SL: 0.92
Prior_Edu_Postcode_6865_CZ - Prior_Edu_School_Location_DOORWERTH: 1.00
Prior_Edu_Postcode_3401_RD - Prior_Edu_School_Location_IJSSELSTEIN: 1.00
Prior_Edu_Postcode_7414_AR - Prior_Edu_School_Location_DEVENTER: 0.96
Prior_Edu_Postcode_6814_CJ - Prior_Edu_School_Location_ARNHEM: 0.75
Prior_Edu_Country_outside_NL - Prior_Edu_Postcode_0000_ABROAD: 0.91
Prior_Edu_Postcode_4254_XD - Prior_Edu_School_Location_SLEEUWIJK: 1.00
Prior_Edu_Postcode_3761_EV - Prior_Edu_School_Location_SOEST: 1.00
Prior_Edu_Postcode_5262_BS - Prior_Edu_School_Location_VUGHT: 1.00
Prior_Edu_Country_outside_NL - Prior_Edu_School_Location_0000_ABROAD: 0.95
Prior_Edu_Postcode_4873_LP - Prior_Edu_School_Location_ETTEN-LEUR: 0.95
Prior_Edu_Postcode_3742_CS - Prior_Edu_School_Location_BAARN: 1.00
Prior_Edu_Postcode_2321_KS - Prior_Edu_School_Location_LEIDEN: 0.82
Prior_Edu_Postcode_3446_GL - Prior_Edu_School_Location_WOERDEN: 0.77
Prior_Edu_Postcode_3851_ZJ - Prior_Edu_School_Location_ERMELO: 1.00
Prior_Edu_Postcode_4103_NM - Prior_Edu_School_Location_CULEMBORG: 0.86
Prior_Edu_Postcode_1102_CV - Prior_Edu_School_Location_AMSTERDAM: 0.73
Prior_Edu_Postcode_1276_KD - Prior_Edu_School_Location_HUIZEN: 0.72
Prior_Edu_Postcode_3723_BA - Prior_Edu_School_Location_BILTHOVEN: 0.70
Prior_Edu_Postcode_4535_HA - Prior_Edu_School_Location_TERNEUZEN: 0.85
Prior_Edu_Postcode_6904_GZ - Prior_Edu_School_Location_ZEVENAAR: 1.00
Prior_Edu_Postcode_6706_KN - Prior_Edu_School_Location_WAGENINGEN: 0.97
Prior_Edu_Postcode_2871_JN - Prior_Edu_School_Location_SCHOONHOVEN: 0.76
Prior_Edu_Postcode_3962_KT - Prior_Edu_School_Location_WIJK_BIJ_DUURSTEDE: 1.00
Prior_Edu_Postcode_8081_VV - Prior_Edu_School_Location_ELBURG: 1.00

Iteratively remove one of the columns from the highly correlated pairs until all remaining columns have a correlation of less than 0.7

In [22]:
# Drop Enrollment_ID (since it's just an identifier)
data_numeric = data.drop(columns=['Enrollment_ID'])

# Compute correlation matrix
corr_matrix = data_numeric.corr()

# Threshold for high correlation
threshold = 0.7

# Identify pairs of highly correlated columns
high_corr_pairs = set()
for col1 in corr_matrix.columns:
    for col2 in corr_matrix.columns:
        if col1 != col2 and corr_matrix.loc[col1, col2] > threshold:
            high_corr_pairs.add((col1, col2))

# Identify columns to remove to reduce correlation
columns_to_remove = set()
for col1, col2 in high_corr_pairs:
    if col1 not in columns_to_remove and col2 not in columns_to_remove:
        columns_to_remove.add(col2)  # Remove one of the highly correlated columns

# Keep only uncorrelated columns (less than 0.7 correlation)
final_columns = [col for col in data_numeric.columns if col not in columns_to_remove]
data_final = data_numeric[final_columns]

# Show the remaining columns and the first few rows
print("Remaining Columns After Removing High Correlation:")
print(data_final.columns)
print("\nData Preview:")
data_final

Remaining Columns After Removing High Correlation:
Index(['Study_Prog_Exam_Completed', 'Study_Prog_Group_Size',
       'Student_Enrollment_Gap', 'Exit_Status', 'Study_Prog_Name_Accountancy',
       'Study_Prog_Name_Allied_Medical_Care', 'Study_Prog_Name_Arts_Therapies',
       'Study_Prog_Name_Bachelor_of_Law',
       'Study_Prog_Name_Biology_Medical_Laboratory_Research',
       'Study_Prog_Name_Built_Environment',
       ...
       'Prior_Edu_Postcode_7414_AR', 'Prior_Edu_Postcode_8017_CA',
       'Prior_Edu_Postcode_8024_AH', 'Prior_Edu_Postcode_8031_AA',
       'Prior_Edu_Postcode_8081_VV', 'Prior_Edu_Postcode_8233_GA',
       'Prior_Edu_Postcode_8932_NX', 'Prior_Edu_Postcode_9723_ZS',
       'Prior_Edu_Postcode_Others', 'Prior_Edu_Country_NL'],
      dtype='object', length=246)

Data Preview:

,Study_Prog_Exam_Completed,Study_Prog_Group_Size,Student_Enrollment_Gap,Exit_Status,Study_Prog_Name_Accountancy,Study_Prog_Name_Allied_Medical_Care,Study_Prog_Name_Arts_Therapies,Study_Prog_Name_Bachelor_of_Law,Study_Prog_Name_Biology_Medical_Laboratory_Research,Study_Prog_Name_Built_Environment,Study_Prog_Name_Business_Administration,Study_Prog_Name_Cesar_Kinetics_Therapy,Study_Prog_Name_Chemical_Engineering,Study_Prog_Name_Chemistry,Study_Prog_Name_Communication,Study_Prog_Name_Communication_and_Multimedia_Design,Study_Prog_Name_Creative_Business,Study_Prog_Name_Dental_Hygiene,Study_Prog_Name_Educational_Theory,Study_Prog_Name_Electrical_and_Electronic_Engineering,Study_Prog_Name_Entrepreneurship_Retail_Management,Study_Prog_Name_Facility_Management,Study_Prog_Name_Finance_Control,Study_Prog_Name_Finance_Tax_and_Advice,Study_Prog_Name_Health_Care_Management,Study_Prog_Name_Human_Resource_Management,Study_Prog_Name_Industrial_Engineering_Management,Study_Prog_Name_Information_Communication_Technology,Study_Prog_Name_International_Business_Utrecht,Study_Prog_Name_Interpreter,Study_Prog_Name_Journalism,Study_Prog_Name_Logistics_Management,Study_Prog_Name_Marketing_Management,Study_Prog_Name_Mechanical_Engineering,Study_Prog_Name_Nursing,Study_Prog_Name_Optometry,Study_Prog_Name_Orthoptics,Study_Prog_Name_Pharmaceutical_Business_Administration,Study_Prog_Name_Physiotherapy,Study_Prog_Name_Primary_Education,Study_Prog_Name_Safety_and_Security_Management,Study_Prog_Name_Skin_Therapy,Study_Prog_Name_Social_Legal_Services,Study_Prog_Name_Social_Work,Study_Prog_Name_Speech_and_Language_Therapy,Study_Prog_Name_Teacher_Education,Prior_Edu_Type_BUITENL_SL,Prior_Edu_Type_EDUCATIE,Prior_Edu_Type_HAVO,Prior_Edu_Type_HBO,Prior_Edu_Type_MBO,Prior_Edu_Type_OVERIG,Prior_Edu_Type_Others,Prior_Edu_Type_VWO,Prior_Edu_School_Location_'S-GRAVENHAGE,Prior_Edu_School_Location_ALMELO,Prior_Edu_School_Location_ALMERE,Prior_Edu_School_Location_ALPHEN_AAN_DEN_RIJN,Prior_Edu_School_Location_AMERSFOORT,Prior_Edu_School_Location_AMSTELVEEN,Prior_Edu_School_Location_APELDOORN,Prior_Edu_School_Location_ASSEN,Prior_Edu_School_Location_BAARN,Prior_Edu_School_Location_BARNEVELD,Prior_Edu_School_Location_BERGEN_NH,Prior_Edu_School_Location_BREDA,Prior_Edu_School_Location_BUSSUM,Prior_Edu_School_Location_CAPELLE_AAN_DEN_IJSSEL,Prior_Edu_School_Location_DELFT,Prior_Edu_School_Location_EDE,Prior_Edu_School_Location_ENSCHEDE,Prior_Edu_School_Location_ERMELO,Prior_Edu_School_Location_ETTEN-LEUR,Prior_Edu_School_Location_GORINCHEM,Prior_Edu_School_Location_GOUDA,Prior_Edu_School_Location_GRONINGEN,Prior_Edu_School_Location_HAARLEM,Prior_Edu_School_Location_HELMOND,Prior_Edu_School_Location_HENGELO_OV,Prior_Edu_School_Location_HILVERSUM,Prior_Edu_School_Location_HOOFDDORP,Prior_Edu_School_Location_HOORN_NH,Prior_Edu_School_Location_HOUTEN,Prior_Edu_School_Location_IJSSELSTEIN,Prior_Edu_School_Location_LEERDAM,Prior_Edu_School_Location_LEEUWARDEN,Prior_Edu_School_Location_MAASTRICHT,Prior_Edu_School_Location_NIEUWEGEIN,Prior_Edu_School_Location_NIJKERK,Prior_Edu_School_Location_NIJMEGEN,Prior_Edu_School_Location_ONBEKEND,Prior_Edu_School_Location_Others,Prior_Edu_School_Location_PAPENDRECHT,Prior_Edu_School_Location_PURMEREND,Prior_Edu_School_Location_ROTTERDAM,Prior_Edu_School_Location_SCHOONHOVEN,Prior_Edu_School_Location_SLEEUWIJK,Prior_Edu_School_Location_TERNEUZEN,Prior_Edu_School_Location_TIEL,Prior_Edu_School_Location_TILBURG,Prior_Edu_School_Location_UITHOORN,Prior_Edu_School_Location_UTRECHT,Prior_Edu_School_Location_VEENENDAAL,Prior_Edu_School_Location_VLEUTEN,Prior_Edu_School_Location_VOORBURG,Prior_Edu_School_Location_VUGHT,Prior_Edu_School_Location_WAGENINGEN,Prior_Edu_School_Location_WARNSVELD,Prior_Edu_School_Location_WIJK_BIJ_DUURSTEDE,Prior_Edu_School_Location_ZALTBOMMEL,Prior_Edu_School_Location_ZEIST,Prior_Edu_School_Location_ZOETERMEER,Prior_Edu_School_Location_ZUTPHEN,Prior_Edu_School_Location_ZWOLLE,Prior_Edu_Postcode_1033_SB,Prior_Edu_Postcode_1071_ED,Prior_Edu_Postcode_1078_VN,Prior_Edu_Postcode_1097_DZ,Prior_Edu_Postcode_1102_CV,Prior_Edu_Postcode_1211_EN,Prior_Edu_Postcode_1213_VB,Prior_Edu_Postcode_1215_PN,Prior_Edu_Postcode_1217_GH,Prior_Edu_Postcode_1217_PM,Prior_Edu_Postcode_1251_GB,Prior_Edu_Postcode_1273_JP,Prior_Edu_Postcode_1276_KD,Prior_Edu_Postcode_1325_PL,Prior_Edu_Postcode_1326_AA,Prior_Edu_Postcode_1333_VD,Prior_Edu_Postcode_1334_PA,Prior_Edu_Postcode_1382_CD,Prior_Edu_Postcode_1401_RT,Prior_Edu_Postcode_1405_HM,Prior_Edu_Postcode_1406_NR,Prior_Edu_Postcode_1507_EK,Prior_Edu_Postcode_1817_BC,Prior_Edu_Postcode_1902_GT,Prior_Edu_Postcode_2012_BL,Prior_Edu_Postcode_2012_MN,Prior_Edu_Postcode_2012_WT,Prior_Edu_Postcode_2321_KS,Prior_Edu_Postcode_2334_CP,Prior_Edu_Postcode_2401_XH,Prior_Edu_Postcode_2402_NM,Prior_Edu_Postcode_2405_VS,Prior_Edu_Postcode_2521_DB,Prior_Edu_Postcode_2722_ZA,Prior_Edu_Postcode_2803_ZV,Prior_Edu_Postcode_2805_BP,Prior_Edu_Postcode_2805_SN,Prior_Edu_Postcode_2806_HP,Prior_Edu_Postcode_2871_HJ,Prior_Edu_Postcode_3015_CX,Prior_Edu_Postcode_3032_AD,Prior_Edu_Postcode_3034_PT,Prior_Edu_Postcode_3067_MR,Prior_Edu_Postcode_3068_AV,Prior_Edu_Postcode_3071_AL,Prior_Edu_Postcode_3312_KW,Prior_Edu_Postcode_3432_NA,Prior_Edu_Postcode_3435_XA,Prior_Edu_Postcode_3439_MV,Prior_Edu_Postcode_3443_CT,Prior_Edu_Postcode_3446_GL,Prior_Edu_Postcode_3511_XX,Prior_Edu_Postcode_3512_VS,Prior_Edu_Postcode_3513_EX,Prior_Edu_Postcode_3521_GH,Prior_Edu_Postcode_3524_SG,Prior_Edu_Postcode_3526_AB,Prior_Edu_Postcode_3526_HL,Prior_Edu_Postcode_3527_XL,Prior_Edu_Postcode_3544_DA,Prior_Edu_Postcode_3562_CS,Prior_Edu_Postcode_3571_KH,Prior_Edu_Postcode_3572_LP,Prior_Edu_Postcode_3582_KA,Prior_Edu_Postcode_3607_GK,Prior_Edu_Postcode_3621_JK,Prior_Edu_Postcode_3641_XR,Prior_Edu_Postcode_3703_CV,Prior_Edu_Postcode_3706_TE,Prior_Edu_Postcode_3707_EP,Prior_Edu_Postcode_3707_GL,Prior_Edu_Postcode_3708_AG,Prior_Edu_Postcode_3723_BV,Prior_Edu_Postcode_3761_EV,Prior_Edu_Postcode_3813_DC,Prior_Edu_Postcode_3813_DH,Prior_Edu_Postcode_3813_KD,Prior_Edu_Postcode_3813_VD,Prior_Edu_Postcode_3815_AG,Prior_Edu_Postcode_3817_EZ,Prior_Edu_Postcode_3817_KB,Prior_Edu_Postcode_3818_ET,Prior_Edu_Postcode_3818_KG,Prior_Edu_Postcode_3818_LA,Prior_Edu_Postcode_3822_CK,Prior_Edu_Postcode_3825_MP,Prior_Edu_Postcode_3842_LA,Prior_Edu_Postcode_3844_AS,Prior_Edu_Postcode_3904_JC,Prior_Edu_Postcode_3904_ZK,Prior_Edu_Postcode_3906_EA,Prior_Edu_Postcode_3941_ZX,Prior_Edu_Postcode_3995_AX,Prior_Edu_Postcode_4003_KZ,Prior_Edu_Postcode_4102_BM,Prior_Edu_Postcode_4103_NM,Prior_Edu_Postcode_4207_EA,Prior_Edu_Postcode_4818_TA,Prior_Edu_Postcode_5022_DD,Prior_Edu_Postcode_5042_EK,Prior_Edu_Postcode_5216_EG,Prior_Edu_Postcode_5223_GW,Prior_Edu_Postcode_5616_HR,Prior_Edu_Postcode_6042_JZ,Prior_Edu_Postcode_6512_BT,Prior_Edu_Postcode_6525_EN,Prior_Edu_Postcode_6713_MC,Prior_Edu_Postcode_6715_CW,Prior_Edu_Postcode_6717_LG,Prior_Edu_Postcode_6717_XA,Prior_Edu_Postcode_6812_AL,Prior_Edu_Postcode_6814_CJ,Prior_Edu_Postcode_6822_LR,Prior_Edu_Postcode_6824_LE,Prior_Edu_Postcode_6865_CZ,Prior_Edu_Postcode_6904_GZ,Prior_Edu_Postcode_7001_EA,Prior_Edu_Postcode_7313_EC,Prior_Edu_Postcode_7314_NX,Prior_Edu_Postcode_7316_AW,Prior_Edu_Postcode_7329_BZ,Prior_Edu_Postcode_7331_VZ,Prior_Edu_Postcode_7414_AR,Prior_Edu_Postcode_8017_CA,Prior_Edu_Postcode_8024_AH,Prior_Edu_Postcode_8031_AA,Prior_Edu_Postcode_8081_VV,Prior_Edu_Postcode_8233_GA,Prior_Edu_Postcode_8932_NX,Prior_Edu_Postcode_9723_ZS,Prior_Edu_Postcode_Others,Prior_Edu_Country_NL
0,1,347,164.0,2,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
1,0,347,68.0,2,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
2,1,347,49.0,2,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1
3,0,347,11.0,2,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
4,1,347,63.0,2,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48386,0,1663,51.0,2,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1
48387,0,1663,51.0,2,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1
48388,1,1663,-16.0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
48389,0,1663,99.0,2,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
48390,1,1663,208.0,2,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1

We see 246 columns left out of 301

In [23]:
data_final.to_csv(os.path.join("..", "data", "processed", "removed_high_corr.csv"), header=True)

In [24]:
data = data_final
data

,Study_Prog_Exam_Completed,Study_Prog_Group_Size,Student_Enrollment_Gap,Exit_Status,Study_Prog_Name_Accountancy,Study_Prog_Name_Allied_Medical_Care,Study_Prog_Name_Arts_Therapies,Study_Prog_Name_Bachelor_of_Law,Study_Prog_Name_Biology_Medical_Laboratory_Research,Study_Prog_Name_Built_Environment,Study_Prog_Name_Business_Administration,Study_Prog_Name_Cesar_Kinetics_Therapy,Study_Prog_Name_Chemical_Engineering,Study_Prog_Name_Chemistry,Study_Prog_Name_Communication,Study_Prog_Name_Communication_and_Multimedia_Design,Study_Prog_Name_Creative_Business,Study_Prog_Name_Dental_Hygiene,Study_Prog_Name_Educational_Theory,Study_Prog_Name_Electrical_and_Electronic_Engineering,Study_Prog_Name_Entrepreneurship_Retail_Management,Study_Prog_Name_Facility_Management,Study_Prog_Name_Finance_Control,Study_Prog_Name_Finance_Tax_and_Advice,Study_Prog_Name_Health_Care_Management,Study_Prog_Name_Human_Resource_Management,Study_Prog_Name_Industrial_Engineering_Management,Study_Prog_Name_Information_Communication_Technology,Study_Prog_Name_International_Business_Utrecht,Study_Prog_Name_Interpreter,Study_Prog_Name_Journalism,Study_Prog_Name_Logistics_Management,Study_Prog_Name_Marketing_Management,Study_Prog_Name_Mechanical_Engineering,Study_Prog_Name_Nursing,Study_Prog_Name_Optometry,Study_Prog_Name_Orthoptics,Study_Prog_Name_Pharmaceutical_Business_Administration,Study_Prog_Name_Physiotherapy,Study_Prog_Name_Primary_Education,Study_Prog_Name_Safety_and_Security_Management,Study_Prog_Name_Skin_Therapy,Study_Prog_Name_Social_Legal_Services,Study_Prog_Name_Social_Work,Study_Prog_Name_Speech_and_Language_Therapy,Study_Prog_Name_Teacher_Education,Prior_Edu_Type_BUITENL_SL,Prior_Edu_Type_EDUCATIE,Prior_Edu_Type_HAVO,Prior_Edu_Type_HBO,Prior_Edu_Type_MBO,Prior_Edu_Type_OVERIG,Prior_Edu_Type_Others,Prior_Edu_Type_VWO,Prior_Edu_School_Location_'S-GRAVENHAGE,Prior_Edu_School_Location_ALMELO,Prior_Edu_School_Location_ALMERE,Prior_Edu_School_Location_ALPHEN_AAN_DEN_RIJN,Prior_Edu_School_Location_AMERSFOORT,Prior_Edu_School_Location_AMSTELVEEN,Prior_Edu_School_Location_APELDOORN,Prior_Edu_School_Location_ASSEN,Prior_Edu_School_Location_BAARN,Prior_Edu_School_Location_BARNEVELD,Prior_Edu_School_Location_BERGEN_NH,Prior_Edu_School_Location_BREDA,Prior_Edu_School_Location_BUSSUM,Prior_Edu_School_Location_CAPELLE_AAN_DEN_IJSSEL,Prior_Edu_School_Location_DELFT,Prior_Edu_School_Location_EDE,Prior_Edu_School_Location_ENSCHEDE,Prior_Edu_School_Location_ERMELO,Prior_Edu_School_Location_ETTEN-LEUR,Prior_Edu_School_Location_GORINCHEM,Prior_Edu_School_Location_GOUDA,Prior_Edu_School_Location_GRONINGEN,Prior_Edu_School_Location_HAARLEM,Prior_Edu_School_Location_HELMOND,Prior_Edu_School_Location_HENGELO_OV,Prior_Edu_School_Location_HILVERSUM,Prior_Edu_School_Location_HOOFDDORP,Prior_Edu_School_Location_HOORN_NH,Prior_Edu_School_Location_HOUTEN,Prior_Edu_School_Location_IJSSELSTEIN,Prior_Edu_School_Location_LEERDAM,Prior_Edu_School_Location_LEEUWARDEN,Prior_Edu_School_Location_MAASTRICHT,Prior_Edu_School_Location_NIEUWEGEIN,Prior_Edu_School_Location_NIJKERK,Prior_Edu_School_Location_NIJMEGEN,Prior_Edu_School_Location_ONBEKEND,Prior_Edu_School_Location_Others,Prior_Edu_School_Location_PAPENDRECHT,Prior_Edu_School_Location_PURMEREND,Prior_Edu_School_Location_ROTTERDAM,Prior_Edu_School_Location_SCHOONHOVEN,Prior_Edu_School_Location_SLEEUWIJK,Prior_Edu_School_Location_TERNEUZEN,Prior_Edu_School_Location_TIEL,Prior_Edu_School_Location_TILBURG,Prior_Edu_School_Location_UITHOORN,Prior_Edu_School_Location_UTRECHT,Prior_Edu_School_Location_VEENENDAAL,Prior_Edu_School_Location_VLEUTEN,Prior_Edu_School_Location_VOORBURG,Prior_Edu_School_Location_VUGHT,Prior_Edu_School_Location_WAGENINGEN,Prior_Edu_School_Location_WARNSVELD,Prior_Edu_School_Location_WIJK_BIJ_DUURSTEDE,Prior_Edu_School_Location_ZALTBOMMEL,Prior_Edu_School_Location_ZEIST,Prior_Edu_School_Location_ZOETERMEER,Prior_Edu_School_Location_ZUTPHEN,Prior_Edu_School_Location_ZWOLLE,Prior_Edu_Postcode_1033_SB,Prior_Edu_Postcode_1071_ED,Prior_Edu_Postcode_1078_VN,Prior_Edu_Postcode_1097_DZ,Prior_Edu_Postcode_1102_CV,Prior_Edu_Postcode_1211_EN,Prior_Edu_Postcode_1213_VB,Prior_Edu_Postcode_1215_PN,Prior_Edu_Postcode_1217_GH,Prior_Edu_Postcode_1217_PM,Prior_Edu_Postcode_1251_GB,Prior_Edu_Postcode_1273_JP,Prior_Edu_Postcode_1276_KD,Prior_Edu_Postcode_1325_PL,Prior_Edu_Postcode_1326_AA,Prior_Edu_Postcode_1333_VD,Prior_Edu_Postcode_1334_PA,Prior_Edu_Postcode_1382_CD,Prior_Edu_Postcode_1401_RT,Prior_Edu_Postcode_1405_HM,Prior_Edu_Postcode_1406_NR,Prior_Edu_Postcode_1507_EK,Prior_Edu_Postcode_1817_BC,Prior_Edu_Postcode_1902_GT,Prior_Edu_Postcode_2012_BL,Prior_Edu_Postcode_2012_MN,Prior_Edu_Postcode_2012_WT,Prior_Edu_Postcode_2321_KS,Prior_Edu_Postcode_2334_CP,Prior_Edu_Postcode_2401_XH,Prior_Edu_Postcode_2402_NM,Prior_Edu_Postcode_2405_VS,Prior_Edu_Postcode_2521_DB,Prior_Edu_Postcode_2722_ZA,Prior_Edu_Postcode_2803_ZV,Prior_Edu_Postcode_2805_BP,Prior_Edu_Postcode_2805_SN,Prior_Edu_Postcode_2806_HP,Prior_Edu_Postcode_2871_HJ,Prior_Edu_Postcode_3015_CX,Prior_Edu_Postcode_3032_AD,Prior_Edu_Postcode_3034_PT,Prior_Edu_Postcode_3067_MR,Prior_Edu_Postcode_3068_AV,Prior_Edu_Postcode_3071_AL,Prior_Edu_Postcode_3312_KW,Prior_Edu_Postcode_3432_NA,Prior_Edu_Postcode_3435_XA,Prior_Edu_Postcode_3439_MV,Prior_Edu_Postcode_3443_CT,Prior_Edu_Postcode_3446_GL,Prior_Edu_Postcode_3511_XX,Prior_Edu_Postcode_3512_VS,Prior_Edu_Postcode_3513_EX,Prior_Edu_Postcode_3521_GH,Prior_Edu_Postcode_3524_SG,Prior_Edu_Postcode_3526_AB,Prior_Edu_Postcode_3526_HL,Prior_Edu_Postcode_3527_XL,Prior_Edu_Postcode_3544_DA,Prior_Edu_Postcode_3562_CS,Prior_Edu_Postcode_3571_KH,Prior_Edu_Postcode_3572_LP,Prior_Edu_Postcode_3582_KA,Prior_Edu_Postcode_3607_GK,Prior_Edu_Postcode_3621_JK,Prior_Edu_Postcode_3641_XR,Prior_Edu_Postcode_3703_CV,Prior_Edu_Postcode_3706_TE,Prior_Edu_Postcode_3707_EP,Prior_Edu_Postcode_3707_GL,Prior_Edu_Postcode_3708_AG,Prior_Edu_Postcode_3723_BV,Prior_Edu_Postcode_3761_EV,Prior_Edu_Postcode_3813_DC,Prior_Edu_Postcode_3813_DH,Prior_Edu_Postcode_3813_KD,Prior_Edu_Postcode_3813_VD,Prior_Edu_Postcode_3815_AG,Prior_Edu_Postcode_3817_EZ,Prior_Edu_Postcode_3817_KB,Prior_Edu_Postcode_3818_ET,Prior_Edu_Postcode_3818_KG,Prior_Edu_Postcode_3818_LA,Prior_Edu_Postcode_3822_CK,Prior_Edu_Postcode_3825_MP,Prior_Edu_Postcode_3842_LA,Prior_Edu_Postcode_3844_AS,Prior_Edu_Postcode_3904_JC,Prior_Edu_Postcode_3904_ZK,Prior_Edu_Postcode_3906_EA,Prior_Edu_Postcode_3941_ZX,Prior_Edu_Postcode_3995_AX,Prior_Edu_Postcode_4003_KZ,Prior_Edu_Postcode_4102_BM,Prior_Edu_Postcode_4103_NM,Prior_Edu_Postcode_4207_EA,Prior_Edu_Postcode_4818_TA,Prior_Edu_Postcode_5022_DD,Prior_Edu_Postcode_5042_EK,Prior_Edu_Postcode_5216_EG,Prior_Edu_Postcode_5223_GW,Prior_Edu_Postcode_5616_HR,Prior_Edu_Postcode_6042_JZ,Prior_Edu_Postcode_6512_BT,Prior_Edu_Postcode_6525_EN,Prior_Edu_Postcode_6713_MC,Prior_Edu_Postcode_6715_CW,Prior_Edu_Postcode_6717_LG,Prior_Edu_Postcode_6717_XA,Prior_Edu_Postcode_6812_AL,Prior_Edu_Postcode_6814_CJ,Prior_Edu_Postcode_6822_LR,Prior_Edu_Postcode_6824_LE,Prior_Edu_Postcode_6865_CZ,Prior_Edu_Postcode_6904_GZ,Prior_Edu_Postcode_7001_EA,Prior_Edu_Postcode_7313_EC,Prior_Edu_Postcode_7314_NX,Prior_Edu_Postcode_7316_AW,Prior_Edu_Postcode_7329_BZ,Prior_Edu_Postcode_7331_VZ,Prior_Edu_Postcode_7414_AR,Prior_Edu_Postcode_8017_CA,Prior_Edu_Postcode_8024_AH,Prior_Edu_Postcode_8031_AA,Prior_Edu_Postcode_8081_VV,Prior_Edu_Postcode_8233_GA,Prior_Edu_Postcode_8932_NX,Prior_Edu_Postcode_9723_ZS,Prior_Edu_Postcode_Others,Prior_Edu_Country_NL
0,1,347,164.0,2,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
1,0,347,68.0,2,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
2,1,347,49.0,2,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1
3,0,347,11.0,2,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
4,1,347,63.0,2,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48386,0,1663,51.0,2,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1
48387,0,1663,51.0,2,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1
48388,1,1663,-16.0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
48389,0,1663,99.0,2,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
48390,1,1663,208.0,2,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1

In [25]:
print(data['Exit_Status'].value_counts())

Exit_Status
2    43154
1     3489
0     1748
Name: count, dtype: int64